import type { Metadata } from 'next';

import { Networks } from '@/lib/networks';
import { LedgerProvider } from '@/providers/ledger-provider';
import { WalletProvider } from '@/providers/wallet-provider';
import { XRPLClientProvider } from '@/providers/xrpl-provider';
import { Inter } from 'next/font/google';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <XRPLClientProvider network={Networks.Testnet}>
          <WalletProvider>
            <LedgerProvider>{children}</LedgerProvider>
          </WalletProvider>
        </XRPLClientProvider>
      </body>
    </html>
  );
}
