import type { Metadata } from 'next';

import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import { Inter } from 'next/font/google';

import './globals.css';
import Header from './header';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

dayjs.extend(utc);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.variable}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
